<small><small><i>
All the IPython Notebooks in this lecture series by Dr. Milan Parmar are available @ **[GitHub](https://github.com/milaan9/09_Python_NumPy_Module)**
</i></small></small>

# Python NumPy Array: 

A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

Numpy array is a powerful N-dimensional array object which is in the form of rows and columns. We can initialize NumPy arrays from nested Python lists and access it elements.

## NumPy Array Types:

<div>
<img src="img/array.png" width="700"/>
</div>

## Create a NumPy Array

Simplest way to create an array in Numpy is to use Python List

### Load in NumPy Library

In [1]:
import numpy as np

In [2]:
my_list = [1,2,3,4]
my_list

[1, 2, 3, 4]

To convert python list to a numpy array by using the object **`np.array`**.

In [3]:
numpy_array_from_list = np.array(my_list)
numpy_array_from_list

array([1, 2, 3, 4])

In practice, there is no need to declare a Python List. The operation can be combined.

In [4]:
my_list1  = np.array([1,2,3,4])
my_list1

array([1, 2, 3, 4])

>**NOTE:** Numpy documentation states use of **`np.ndarray`** to create an array. However, this the recommended method

You can also create a numpy array from a Tuple

In [5]:
my_list2 = np.array (range (1,5))
my_list2

array([1, 2, 3, 4])

## Numpy Array basics 

We can initialize numpy arrays from nested Python lists, and access elements using square brackets **`[]`**:

In [6]:
a = np.array([1,2,3]) # Create a 1D array
print(a) 
print(type(a))  # Prints "<class 'numpy.ndarray'>"

[1 2 3]
<class 'numpy.ndarray'>


In [7]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [8]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
# Get Dimension
a.ndim

1

In [10]:
# Get Shape
b.shape

(2, 3)

In [11]:
# Get Size
a.itemsize

4

In [12]:
# Get Size
b.itemsize

8

In [13]:
# Get total size
a.nbytes  # a.nbytes = a.size * a.itemsize

12

In [14]:
# Get number of elements
a.size

3

In [15]:
a = np.array([1, 2, 3])   # Create a 1d array
print(a)
print(type(a))            # Prints "<class 'numpy.ndarray'>"
print(a.shape)            # Prints "(3,)"
print(a[0], a[1], a[2])   # Indexing with 3 elements. Prints "1 2 3"
a[0] = 5                  # Change an element of the array
print(a)                  # Prints "[5, 2, 3]"

b = np.array([[1,2,3],[4,5,6]])    # Create a 2d array
print(b)
print(b.shape)                     # Prints "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0])   # Prints "1 2 4"

[1 2 3]
<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
[[1 2 3]
 [4 5 6]]
(2, 3)
1 2 4


## Array datatypes

Every numpy array is a grid of elements of the same type. Numpy provides a large set of numeric datatypes that you can use to construct arrays. Numpy tries to guess a datatype when you create an array, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype. For example:

In [16]:
a = np.array([1,2,3], dtype='int32') # Create a 1D array with int32 type
print(a) 

[1 2 3]


In [17]:
# Get Type
a.dtype

dtype('int32')

In [18]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)
b.dtype

[[9. 8. 7.]
 [6. 5. 4.]]


dtype('float64')

In [19]:
import numpy as np

x = np.array([1, 2])   # Let numpy choose the datatype
print(x.dtype)         # Prints "int64"

x = np.array([1.0, 2.0])   # Let numpy choose the datatype
print(x.dtype)             # Prints "float64"

x = np.array([1, 2], dtype=np.int64)   # Force a particular datatype
print(x.dtype)                         # Prints "int64"

int32
float64
int64


You can read all about numpy datatypes in this **[documentation](https://numpy.org/doc/stable/reference/arrays.dtypes.html)**.

### Random number

#### `rand`
Random values in a given shape from a uniform distribution over [0, 1)

In [20]:
np.random.rand(3)

array([0.26066559, 0.82878994, 0.03269998])

In [21]:
np.random.rand(3,5)

array([[0.72202193, 0.26313176, 0.65527294, 0.86187385, 0.88766704],
       [0.43360347, 0.32797579, 0.53869915, 0.70644234, 0.13186514],
       [0.94814464, 0.91195975, 0.7395529 , 0.30683795, 0.31090551]])

In [22]:
# Random decimal numbers
np.random.rand(4,2)

#or
#np.random.random_sample(a.shape)

array([[0.81703872, 0.33437869],
       [0.53239284, 0.57197812],
       [0.3256678 , 0.36390438],
       [0.01827176, 0.20054309]])

#### `randn`
Return a sample (or samples) from the "standard normal" distribution. Not Uniform.with mean 0 and variance with 1.


In [23]:
np.random.randn(3)

array([ 0.36847658, -0.2557476 ,  1.00290157])

In [24]:
np.random.randn(4,3)

array([[-1.08924912, -0.26667078, -0.39672241],
       [ 0.14679697, -0.37694696, -2.07040238],
       [-0.0508824 ,  1.50888216,  0.97812268],
       [ 1.17572532, -0.57372638,  0.93809   ]])

#### `randint`
Return random integers from **low** (inclusive) to **high** (exclusive).

In [25]:
np.random.randint(2,100)

93

In [26]:
# Random Integer values
np.random.randint(-4,8, size=(3,3))

array([[-1, -3,  2],
       [-2,  6, -1],
       [-3,  0, -1]])

### Array Attributes and Methods


In [27]:
rana = np.random.randint(1,10,8)
rana

array([4, 8, 5, 6, 3, 3, 7, 6])

#### `max`, `min`, `argmax`, `argmin`

In [28]:
rana

array([4, 8, 5, 6, 3, 3, 7, 6])

In [29]:
rana.max()

8

In [30]:
rana.argmax()

1

In [31]:
rana.min()

3

In [32]:
rana.argmin()

4

### Numpy also provides many functions to create arrays:

In [33]:
# Generating Zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [34]:
# All 0s matrix
np.zeros((2,3))  # pass a tupple

array([[0., 0., 0.],
       [0., 0., 0.]])

In [35]:
# Generating Zeros
np.ones(3)       # one function

array([1., 1., 1.])

In [36]:
np.ones(1)*5

array([5.])

In [37]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [38]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [39]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [40]:
# Any other number (full_like)
np.full_like(a, 4)

#or np.full(a.shape, 4)

array([4, 4, 4])

In [41]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [42]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [43]:
import numpy as np

a = np.zeros((2,2))   # Create an array of all zeros
print(a)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"

b = np.ones((1,2))    # Create an array of all ones
print(b)              # Prints "[[ 1.  1.]]"

c = np.full((2,2), 7)  # Create a constant array
print(c)               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"

d = np.eye(2)         # Create a 2x2 identity matrix
print(d)              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"

e = np.random.random((2,2))  # Create an array filled with random values
print(e)                     # Might print "[[ 0.91940167  0.08143941]
                             #               [ 0.68744134  0.87236687]]"

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.82097684 0.98976055]
 [0.87247146 0.4797067 ]]


In [44]:
#Generate matrix

# 1 1 1 1 1
# 1 0 0 0 1
# 1 0 9 0 1
# 1 1 1 1 1

output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


You can read about other methods of array creation in this **[documentation](https://numpy.org/doc/stable/user/basics.creation.html#arrays-creation)**.