<small><small><i>
All the IPython Notebooks in this lecture series by Dr. Milan Parmar are available @ **[GitHub](https://github.com/milaan9/09_Python_NumPy_Module)**
</i></small></small>

## Array indexing

Numpy offers several ways to index into arrays and accessing/changing specific elements, rows, columns, etc.

**Slicing:** Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array:

In [1]:
import numpy as np
a = np.arange(0,11)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### Indexing a 1D array

In [2]:
a[2]           # Get a value at an index

2

In [3]:
a[1:4]         # Get values in a range / slice notation

array([1, 2, 3])

In [4]:
a[:6]

array([0, 1, 2, 3, 4, 5])

In [5]:
a[3:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
#Slices
slice_a = a[0:5]
slice_a

array([0, 1, 2, 3, 4])

In [7]:
slice_a[:]=100
slice_a

array([100, 100, 100, 100, 100])

In [8]:
a         # Change in original array

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [9]:
a_copy = a.copy()   # creat a copy

a_copy

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [10]:
a_copy[:]=200
a_copy

array([200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200])

In [11]:
a

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

##### Be careful when copying arrays!!!

In [12]:
a = np.array([1,2,3])
a
b = a
#b = a.copy()
b[0] = 100

print(a) 

[100   2   3]


#### Indexing a 2D array (matrices)

In [13]:
# mat = [row,col]
# mat = [row][col]

In [14]:
mat=np.array(([5,10,20],[20,25,30],[35,40,10]))
mat

array([[ 5, 10, 20],
       [20, 25, 30],
       [35, 40, 10]])

In [15]:
mat[1] #Indexing row

array([20, 25, 30])

In [16]:
mat[2]

array([35, 40, 10])

In [17]:
# Getting individual element value
mat[1][1]

25

In [18]:
mat[1,2] # use common notaion instaed of 2 brackets

30

In [19]:
#array slicing
mat

array([[ 5, 10, 20],
       [20, 25, 30],
       [35, 40, 10]])

In [20]:
#Shape top row
mat[0]

array([ 5, 10, 20])

In [21]:
#Shape (2,2) from top right corner
mat[:2,1:]

array([[10, 20],
       [25, 30]])

In [22]:
#Shape (2,2) from bottom left corner
mat[1:,:2]

array([[20, 25],
       [35, 40]])

In [23]:
#Shape bottom row
mat[2]

array([35, 40, 10])

In [24]:
#Shape bottom row
mat[2,:]

array([35, 40, 10])

In [25]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [26]:
# Get a specific element [row, column]

a[1, 5]  # to select element '13' we need row 2 and element 6. Hence r=1, c=5 (index start from 0)

# or a[1,-2]

13

In [27]:
# Get a specific row 
a[0, :] # all columns

array([1, 2, 3, 4, 5, 6, 7])

In [28]:
# Get a specific column
a[:, 2] # all rows

array([ 3, 10])

In [29]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

In [30]:
a[1,5] = 20  # row 2 and element 6
print(a)

a[:,2] = [1,2]
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [31]:
# 3D example

b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [32]:
# Get specific element (work outside in)
b[0,1,1]

4

In [33]:
# replace 
b[:,1,:]
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [34]:
b[:,1,:] = [[9,9,9],[8,8]]
print(b)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

#### Summary:

In [35]:
import numpy as np

import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print(b)

# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print(a[0, 1])   # Prints "2"
b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])   # Prints "77"

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]
2
77


You can also mix **integer indexing** with **slice indexing**. However, doing so will yield an array of lower rank than the original array. 

>**Note:** this is quite different from the way that MATLAB handles array slicing:

In [36]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

# Two ways of accessing the data in the middle row of the array.
# Mixing integer indexing with slices yields an array of lower rank,
# while using only slices yields an array of the same rank as the
# original array:
row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)  # Prints "[5 6 7 8] (4,)"
print(row_r2, row_r2.shape)  # Prints "[[5 6 7 8]] (1, 4)"

# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)  # Prints "[ 2  6 10] (3,)"
print(col_r2, col_r2.shape)  # Prints "[[ 2]
                             #          [ 6]
                             #          [10]] (3, 1)"

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


### Integer array indexing

When you index into numpy arrays using slicing, the resulting array view will always be a subarray of the original array. In contrast, integer array indexing allows you to construct arbitrary arrays using the data from another array. Here is an example:

In [37]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])
print(a)

# An example of integer array indexing.
# The returned array will have shape (3,) and
print(a[[0, 1, 2], [0, 1, 0]])  # Prints "[1 4 5]"

# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))  # Prints "[1 4 5]"

# When using integer array indexing, you can reuse the same
# element from the source array:
print(a[[0, 0], [1, 1]])  # Prints "[2 2]"

# Equivalent to the previous integer array indexing example
print(np.array([a[0, 1], a[0, 1]]))  # Prints "[2 2]"

[[1 2]
 [3 4]
 [5 6]]
[1 4 5]
[1 4 5]
[2 2]
[2 2]


One useful trick with integer array indexing is selecting or mutating one element from each row of a matrix:

In [38]:
import numpy as np

# Create a new array from which we will select elements
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])

print(a)  # prints "array([[ 1,  2,  3],
          #                [ 4,  5,  6],
          #                [ 7,  8,  9],
          #                [10, 11, 12]])"

# Create an array of indices
b = np.array([0, 2, 0, 1])

# Select one element from each row of a using the indices in b
print(a[np.arange(4), b])  # Prints "[ 1  6  7 11]"

# Mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 10

print(a)  # prints "array([[11,  2,  3],
          #                [ 4,  5, 16],
          #                [17,  8,  9],
          #                [10, 21, 12]])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


### Quiz time

In [ ]:
# Generate matrix:

###    1  2  3  4  5
###    6  7  8  9 10
###   11 12 13 14 15
###   16 17 18 19 20
###   21 22 23 24 25
###   26 27 28 29 30

# Acces 
        11 12
        16 17
    
# Acces  
         2
           8
            14
              20

# Acces        
                4  5



               24 25
               29 30

### Boolean array indexing

Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition. Here is an example:

In [39]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
a > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [41]:
bool_a = a>4

In [42]:
bool_a

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [43]:
a[bool_a]

array([ 5,  6,  7,  8,  9, 10])

In [44]:
a[a>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
x = 2
a[a>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [46]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])
print(a)

bool_idx = (a > 2)   # Find the elements of a that are bigger than 2;
                     # this returns a numpy array of Booleans of the same
                     # shape as a, where each slot of bool_idx tells
                     # whether that element of a is > 2.

print(bool_idx)      # Prints "[[False False]
                     #          [ True  True]
                     #          [ True  True]]"

# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx])  # Prints "[3 4 5 6]"

# We can do all of the above in a single concise statement:
print(a[a > 2])     # Prints "[3 4 5 6]"

[[1 2]
 [3 4]
 [5 6]]
[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


For brevity we have left out a lot of details about numpy array indexing; if you want to know more about Array Indexing you should read this **[documentation](https://numpy.org/doc/stable/reference/arrays.indexing.html)**.