<small><small><i>
All the IPython Notebooks in this lecture series by Dr. Milan Parmar are available @ **[GitHub](https://github.com/milaan9/09_Python_NumPy_Module)**
</i></small></small>

## Arrays reorganizing

### `asarray()`

The **`asarray()`** function is used when you want to convert an input to an array. The input could be a lists, tuple, ndarray, etc.

**Syntax:**
```python
numpy.asarray(data, dtype=None, order=None)[source]
```

* **`data`**: Data that you want to convert to an array

* **`dtype`**: This is an optional argument. If not specified, the data type is inferred from the input data

* **`Order`**: Default is **`C`** which is an essential row style. Other option is **`F`** (Fortan-style)

In [1]:
# Consider the following 2-D matrix with four rows and four columns filled by 1

import numpy as np

a = np.matrix(np.ones((4,4)))


If you want to change the value of the matrix, you cannot. The reason is, it is not possible to change a copy.

In [2]:
np.array(a)[2]=3
print(a)  # value won't change in result

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


Matrix is immutable. You can use asarray if you want to add modification in the original array. Let's see if any change occurs when you want to change the value of the third rows with the value 2

In [3]:
np.asarray(a)[2]=2 # np.asarray(A): converts the matrix A to an array
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [1. 1. 1. 1.]]


### `arange()`

The **`arange()`** is an inbuilt numpy function that returns an ndarray object containing evenly spaced values within a defined interval. For instance, you want to create values from 1 to 10; you can use **`arange()`** function.

**Syntax:**
```python
numpy.arange(start, stop,step) 
```
* **`start`**: Start of interval
* **`stop`**: End of interval
* **`step`**: Spacing between values. Default step is 1

In [4]:
# Example 1:

import numpy as np
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

If you want to change the step, you can add a third number in the parenthesis. It will change the step.

In [5]:
# Example 2:

import numpy as np
np.arange(1, 14, 4)

array([ 1,  5,  9, 13])

In [6]:
np.arange(0,11,2)   # even no by adding a step size

array([ 0,  2,  4,  6,  8, 10])

In [7]:
np.arange(1,11,2)   # odd no

array([1, 3, 5, 7, 9])

### Reshape Data

In some occasions, you need to reshape the data from wide to long. You can use the reshape function for this. 

**Syntax:** 
```python
numpy.reshape(a, newShape, order='C')
```
* **`a: Array`** that you want to reshape
* **`newShape`**: The new desires shape
* **`order`**: Default is **`C`** which is an essential row style.

In [8]:
import numpy as np

e  = np.array([(1,2,3), (4,5,6)])
print(e)
e.reshape(3,2)

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [9]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((2,4))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]]


### Flatten Data

When you deal with some neural network like convnet, you need to flatten the array. You can use **`flatten()`**.

**Syntax:** 
```python
numpy.flatten(order='C')
```
* **`a: Array`** that you want to reshape
* **`newShape`**: The new desires shape
* **`order`**: Default is **`C`** which is an essential row style.

In [10]:
e.flatten()

array([1, 2, 3, 4, 5, 6])

### What is `hstack`?

With **`hstack`** you can appened data horizontally. This is a very convinient function in Numpy. Lets study it with an example:

In [11]:
## Horitzontal Stack

import numpy as np
f = np.array([1,2,3])
g = np.array([4,5,6])

print('Horizontal Append:', np.hstack((f, g)))

Horizontal Append: [1 2 3 4 5 6]


In [12]:
# Horizontal  stack

h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### What is `vstack`?

With **`vstack`** you can appened data vertically. Lets study it with an example:

In [13]:
## Vertical Stack

import numpy as np
f = np.array([1,2,3])
g = np.array([4,5,6])

print('Vertical Append:', np.vstack((f, g)))

Vertical Append: [[1 2 3]
 [4 5 6]]


In [14]:
# Vertically stacking vectors

v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

### Generate Random Numbers

To generate random numbers for Gaussian distribution use:

**Syntax:**
```python
numpy.random.normal(loc, scale, size)
```
* **`loc`**: the mean. The center of distribution
* **`scale`**: standard deviation.
* **`size`**: number of returns

In [15]:
## Generate random nmber from normal distribution

normal_array = np.random.normal(5, 0.5, 10)
print(normal_array)

[5.03567032 4.51165007 4.46729965 5.3153469  4.98034071 4.66229247
 4.90315613 5.13908445 5.29644502 5.15711881]


### Linspace

Linspace gives evenly spaced samples.

**Syntax:**
```python
numpy.linspace(start, stop, num, endpoint)
```
* **`start`**: Start of sequence
* **`stop`**: End of sequence
* **`num`**: Number of samples to generate. Default is 50
* **`endpoint`**: If **`True`** (default), stop is the last value. If **`False`**, stop value is not included.

In [16]:
# Example:

import numpy as np
np.linspace(0,10,6) 

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [17]:
# Example: For instance, it can be used to create 10 values from 1 to 5 evenly spaced.

import numpy as np
np.linspace(1.0, 5.0, num=10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

If you do not want to include the last digit in the interval, you can set endpoint to **`False`**

In [18]:
np.linspace(1.0, 5.0, num=5, endpoint=False)

array([1. , 1.8, 2.6, 3.4, 4.2])

### LogSpace

LogSpace returns even spaced numbers on a log scale. Logspace has the same parameters as **`np.linspace`**.

**Syntax:**
```python
numpy.logspace(start, stop, num, endpoint)
```
* **`start`**: Start of sequence
* **`stop`**: End of sequence
* **`num`**: Number of samples to generate. Default is 50
* **`endpoint`**: If **`True`** (default), stop is the last value. If **`False`**, stop value is not included.

In [19]:
# Example:

np.logspace(3.0, 4.0, num=4)

array([ 1000.        ,  2154.43469003,  4641.58883361, 10000.        ])

Finaly, if you want to check the memory size of an element in an array, you can use **`.itemsize`**

In [20]:
x = np.array([1,2,3], dtype=np.complex128)
x.itemsize

16

## Statistics

NumPy has quite a few useful statistical functions for finding minimum, maximum, percentile standard deviation and variance, etc from the given elements in the array. The functions are explained as follows −

Numpy is equipped with the robust statistical function as listed below:

| Function | Numpy |
|:----: |:---- |
| **`Min`**                | **np.min()** | 
| **`Max`**                | **np.max()** | 
| **`Mean`**               | **np.mean()** | 
| **`Median`**             | **np.median()** | 
| **`Standard deviation`** | **np.std()** | 

In [21]:
# Consider the following Array

import numpy as np

normal_array = np.random.normal(5, 0.5, 10)
print(normal_array)	

[4.80529203 5.393371   4.25822467 5.37390133 5.20571071 5.95198887
 6.06342592 5.64144604 6.22347788 5.32099202]


In [22]:
# Example:Statistical function

### Min 
print(np.min(normal_array))

### Max 
print(np.max(normal_array))

### Mean 
print(np.mean(normal_array))

### Median
print(np.median(normal_array))

### Sd
print(np.std(normal_array))

4.258224665595587
6.22347788261574
5.42378304777011
5.3836361690135845
0.5637043104845421


In [23]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
np.min(stats)

1

In [25]:
np.max(stats, axis=1)

array([3, 6])

In [26]:
np.sum(stats, axis=0)

array([5, 7, 9])

## Miscellaneous

### Load Data from File

you can download the "data.txt" from **[here](https://github.com/milaan9/09_Python_NumPy_Module/blob/main/data.txt)**

In [27]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32') # you can also change type to 'int64'
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


### Boolean Masking and Advanced Indexing

In [28]:
filedata >50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [29]:
print(filedata)
filedata[filedata >50] # '[]' will display the value of data point from the dataset

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [30]:
print(filedata)
np.any(filedata > 50, axis = 0) # axis=0 refers to columns and axis=1 refers to rows in this dataset

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [31]:
print(filedata)
np.all(filedata > 50, axis = 0) # '.all' refers to all the data points in row/column (based on axis=0 or axis=1).

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [32]:
print(filedata)
(((filedata > 50) & (filedata < 100)))

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [33]:
print(filedata)
(~((filedata > 50) & (filedata < 100)))  # '~' means not

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

In [34]:
### You can index with a list in NumPy
a = np.array([1,2,3,4,5,6,7,8,9])
a [[1,2,8]] #indexes

array([2, 3, 9])

## Numpy Documentation

This brief overview has touched on many of the important things that you need to know about numpy, but is far from complete. Check out the **[numpy reference](https://numpy.org/doc/stable/reference/)** to find out much more about numpy.